### ISSUE TITLE
Progression vector problem

### ISSUE THREAD

**Issue by adriensizaret** [DART-Lab-LLUI/python-gaitalytics#6]
The progression vector returned by `mocap.get_progression_vector()` is the vector from the hip markers to the sacrum marker, instead of the sacrum to the hip markers as described in the function's docstring.

The function should do: `return (ant_marker - sacrum_marker ).mean(dim="time")`

**Comment by baumi-an** [comment]
Problem is fixed.
It will release with the version 0.2.1
